### ISSUE TITLE
업데이트

### ISSUE THREAD

**Issue by Buu12** [armoha/dis-zero#2]
1.23.7.9198 로 업데이트 했습니다. 킬때마다 오프셋을 계속 해줘야 되는건가요?

![캡처](https://user-images.githubusercontent.com/76092908/102462447-23325680-408d-11eb-86c0-9472f439b391.JPG)

**Comment by Buu12** [comment]
껏다 키면 업데이트 계속 해줘야 되네요
계속 이렇게 해줘야 되나요?

**Comment by armoha** [comment]
PR 넣어주시면 반영할게요.

**Comment by Buu12** [comment]
PR이 어떤거 말씀하시는 건가요?
